use anyhow::{Context, Result};
use std::{collections::HashMap, fs, sync::Arc};
use tokio::sync::{mpsc, Mutex, RwLock};
use tokio_stream::wrappers::ReceiverStream;
use tonic::{transport::Server, Request, Response, Status, Streaming};
use tracing::{info, warn};

// Generated by build.rs from src/proto/tridentd.proto
pub mod tridentd {
    tonic::include_proto!("tridentd");
}

use tridentd::{
    trident_daemon_server::{TridentDaemon, TridentDaemonServer},
    *,
};

// ─────────────────────────────────────────────────────────────────────────────
// Service state
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug)]
struct Instance {
    info: tridentd::InstanceInfo,
    shutdown_tx: Option<tokio::sync::oneshot::Sender<()>>,
}

impl Clone for Instance {
    fn clone(&self) -> Self {
        Self {
            info: self.info.clone(),
            shutdown_tx: None,
        }
    }
}

#[derive(Clone)]
struct TridentService {
    instances: Arc<RwLock<HashMap<String, Instance>>>,
    adb_port_counter: Arc<Mutex<u32>>,
}

impl TridentService {
    fn new() -> Self {
        Self {
            instances: Arc::new(RwLock::new(HashMap::new())),
            adb_port_counter: Arc::new(Mutex::new(5555)),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// gRPC implementation
// ─────────────────────────────────────────────────────────────────────────────

#[tonic::async_trait]
impl TridentDaemon for TridentService {
    // ── Ping ──────────────────────────────────────────────────────────────────
    async fn ping(&self, _req: Request<PingRequest>) -> Result<Response<PingResponse>, Status> {
        let count = self.instances.read().await.len() as u32;
        Ok(Response::new(PingResponse {
            version: env!("CARGO_PKG_VERSION").to_string(),
            instance_count: count,
        }))
    }

    // ── Launch ────────────────────────────────────────────────────────────────
    async fn launch_instance(
        &self,
        req: Request<LaunchRequest>,
    ) -> Result<Response<tridentd::InstanceInfo>, Status> {
        let r = req.into_inner();
        let id = unique_id();
        info!("LaunchInstance id={} kernel={}", id, r.kernel_path);

        let config = crate::vmm::VmConfig {
            vcpu_count: r.vcpu_count.clamp(1, 24) as u8,
            memory_mib: r.memory_mib.clamp(512, 65536),
            kernel_path: r.kernel_path,
            initrd_path: None,
            cmdline: r.cmdline,
            sriov_vf: if r.sriov_vf.is_empty() { None } else { Some(r.sriov_vf) },
            system_image: if r.system_image.is_empty() { None } else { Some(r.system_image) },
            vendor_image: if r.vendor_image.is_empty() { None } else { Some(r.vendor_image) },
            console_sock: Some(format!("/tmp/trident-{id}.sock")),
        };

        let hyp = std::sync::Arc::new(crate::platform::open_hypervisor().map_err(internal)?);
        let vm = crate::vmm::Vm::create(&hyp, config).map_err(internal)?;

        let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel();

        let spawn_id = id.clone();
        tokio::spawn(async move {
            tokio::select! {
                result = vm.run() => {
                    if let Err(e) = result {
                        tracing::error!("VM {} crashed: {:#}", spawn_id, e);
                    }
                }
                _ = shutdown_rx => {
                    info!("VM {} shutdown requested", spawn_id);
                }
            }
        });

        let mut adp = self.adb_port_counter.lock().await;
        let adb_port = *adp;
        *adp += 1;

        let instance_info = tridentd::InstanceInfo {
            instance_id: id.clone(),
            adb_host: "127.0.0.1".to_string(),
            adb_port,
            display_sock: format!("/tmp/trident-{id}-display.sock"),
            state: tridentd::InstanceState::Booting as i32,
        };

        let instance = Instance {
            info: instance_info.clone(),
            shutdown_tx: Some(shutdown_tx),
        };

        self.instances.write().await.insert(id.clone(), instance);

        Ok(Response::new(instance_info))
    }

    // ── Snapshot ──────────────────────────────────────────────────────────────
    async fn snapshot(
        &self,
        req: Request<SnapshotRequest>,
    ) -> Result<Response<SnapshotResponse>, Status> {
        let r = req.into_inner();
        info!("Snapshot instance={} snapshot_id={}", r.instance_id, r.snapshot_id);
        Err(Status::unimplemented("Phase 3"))
    }

    async fn restore_snapshot(
        &self,
        req: Request<RestoreRequest>,
    ) -> Result<Response<tridentd::InstanceInfo>, Status> {
        let r = req.into_inner();
        info!("RestoreSnapshot snapshot_id={}", r.snapshot_id);
        Err(Status::unimplemented("Phase 3"))
    }

    // ── Fork (server-side streaming) ──────────────────────────────────────────
    type ForkStream = ReceiverStream<Result<tridentd::InstanceInfo, Status>>;

    async fn fork(
        &self,
        req: Request<ForkRequest>,
    ) -> Result<Response<Self::ForkStream>, Status> {
        let r = req.into_inner();
        let (tx, rx) = mpsc::channel(4);

        info!("Fork instance={} count={}", r.instance_id, r.count);

        let _service = self.clone();
        tokio::spawn(async move {
            for i in 0..r.count {
                let child_id = format!("{}-fork-{}", r.instance_id, i);
                let info = tridentd::InstanceInfo {
                    instance_id: child_id,
                    adb_host: "127.0.0.1".to_string(),
                    adb_port: 0,
                    display_sock: String::new(),
                    state: tridentd::InstanceState::Booting as i32,
                };
                if tx.send(Ok(info)).await.is_err() {
                    break;
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── ADB shell (bidirectional streaming) ───────────────────────────────────
    type AdbShellStream = ReceiverStream<Result<AdbShellResponse, Status>>;

    async fn adb_shell(
        &self,
        req: Request<Streaming<AdbShellRequest>>,
    ) -> Result<Response<Self::AdbShellStream>, Status> {
        let (tx, rx) = mpsc::channel(64);
        let mut stream = req.into_inner();

        tokio::spawn(async move {
            while let Some(msg) = stream.message().await.unwrap_or(None) {
                let resp = AdbShellResponse {
                    stdout_data: format!("{}\n", String::from_utf8_lossy(&msg.stdin_data)).into_bytes(),
                    stderr_data: vec![],
                    exit_code: 0,
                };
                if tx.send(Ok(resp)).await.is_err() {
                    break;
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── Display streaming ─────────────────────────────────────────────────────
    type StreamDisplayStream = ReceiverStream<Result<DisplayFrame, Status>>;

    async fn stream_display(
        &self,
        req: Request<DisplayStreamRequest>,
    ) -> Result<Response<Self::StreamDisplayStream>, Status> {
        let (tx, rx) = mpsc::channel(16);
        let _r = req.into_inner();

        tokio::spawn(async move {
            let frame = DisplayFrame {
                data: vec![0u8; 1920 * 1080 * 4],
                pts_us: 0,
                key_frame: true,
                width: 1920,
                height: 1080,
            };
            let _ = tx.send(Ok(frame)).await;
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── Stop ──────────────────────────────────────────────────────────────────
    async fn stop_instance(
        &self,
        req: Request<StopRequest>,
    ) -> Result<Response<StopResponse>, Status> {
        let id = req.into_inner().instance_id;
        let mut instances = self.instances.write().await;
        let removed = if let Some(mut instance) = instances.remove(&id) {
            if let Some(tx) = instance.shutdown_tx.take() {
                let _ = tx.send(());
            }
            info!("Stopped instance {id}");
            true
        } else {
            warn!("StopInstance: {id} not found");
            false
        };
        Ok(Response::new(StopResponse { success: removed }))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Server bootstrap — mTLS required (client cert mandatory)
// ─────────────────────────────────────────────────────────────────────────────

pub async fn serve() -> Result<()> {
    let cert = fs::read("certs/server.crt")
        .context("Missing certs/server.crt — run: bash tools/gen_certs.sh")?;
    let key = fs::read("certs/server.key")
        .context("Missing certs/server.key")?;
    let ca = fs::read("certs/ca.crt")
        .context("Missing certs/ca.crt")?;

    let identity = tonic::transport::Identity::from_pem(cert, key);
    let client_ca = tonic::transport::Certificate::from_pem(ca);

    // tonic 0.12: client_auth_optional defaults to false → mTLS enforced
    let tls = tonic::transport::ServerTlsConfig::new()
        .identity(identity)
        .client_ca_root(client_ca);

    let addr = "[::1]:9550".parse().expect("hardcoded addr is valid");
    info!("gRPC/mTLS listening on {}", addr);

    Server::builder()
        .tls_config(tls)
        .context("Failed to configure TLS")?
        .add_service(TridentDaemonServer::new(TridentService::new()))
        .serve(addr)
        .await
        .context("gRPC server error")
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn internal(e: anyhow::Error) -> Status {
    Status::internal(format!("{e:#}"))
}

/// Generate a unique VM id from nanosecond timestamp.
fn unique_id() -> String {
    use std::time::SystemTime;
    let nanos = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos();
    format!("vm-{:08x}", nanos)
}
