use anyhow::{Context, Result};
use std::{fs, sync::Arc};
use tokio::sync::{mpsc, RwLock};
use tokio_stream::wrappers::ReceiverStream;
use tonic::{transport::Server, Request, Response, Status, Streaming};
use tracing::info;

// Generated by build.rs from src/proto/tridentd.proto
pub mod tridentd {
    tonic::include_proto!("tridentd");
}

use tridentd::{
    trident_daemon_server::{TridentDaemon, TridentDaemonServer},
    *,
};

// ─────────────────────────────────────────────────────────────────────────────
// Service state
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct TridentService {
    instances: Arc<RwLock<std::collections::HashMap<String, ()>>>,
}

impl TridentService {
    fn new() -> Self {
        Self { instances: Arc::new(RwLock::new(std::collections::HashMap::new())) }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// gRPC implementation
// ─────────────────────────────────────────────────────────────────────────────

#[tonic::async_trait]
impl TridentDaemon for TridentService {
    // ── Ping ──────────────────────────────────────────────────────────────────
    async fn ping(&self, _req: Request<PingRequest>) -> Result<Response<PingResponse>, Status> {
        let count = self.instances.read().await.len() as u32;
        Ok(Response::new(PingResponse {
            version: env!("CARGO_PKG_VERSION").to_string(),
            instance_count: count,
        }))
    }

    // ── Launch ────────────────────────────────────────────────────────────────
    async fn launch_instance(
        &self,
        req: Request<LaunchRequest>,
    ) -> Result<Response<InstanceInfo>, Status> {
        let r = req.into_inner();
        let id = unique_id();
        info!("LaunchInstance id={} kernel={}", id, r.kernel_path);

        let config = crate::vmm::VmConfig {
            vcpu_count: r.vcpu_count.clamp(1, 24) as u8,
            memory_mib: r.memory_mib.clamp(512, 65536),
            kernel_path: r.kernel_path,
            initrd_path: None,
            cmdline: r.cmdline,
            sriov_vf: if r.sriov_vf.is_empty() { None } else { Some(r.sriov_vf) },
            system_image: if r.system_image.is_empty() { None } else { Some(r.system_image) },
            vendor_image: if r.vendor_image.is_empty() { None } else { Some(r.vendor_image) },
            console_sock: Some(format!("/tmp/trident-{id}.sock")),
        };

        let hyp = std::sync::Arc::new(crate::platform::open_hypervisor().map_err(internal)?);
        let vm = crate::vmm::Vm::create(&hyp, config).map_err(internal)?;

        // Clone id before moving it into the async block
        let spawn_id = id.clone();
        tokio::spawn(async move {
            if let Err(e) = vm.run().await {
                tracing::error!("VM {} crashed: {:#}", spawn_id, e);
            }
        });

        self.instances.write().await.insert(id.clone(), ());

        Ok(Response::new(InstanceInfo {
            instance_id: id,
            adb_host: "127.0.0.1".to_string(),
            adb_port: 5555,
            display_sock: "/tmp/trident-display.sock".to_string(),
            state: InstanceState::Booting as i32,
        }))
    }

    // ── Snapshot ──────────────────────────────────────────────────────────────
    async fn snapshot(
        &self,
        _req: Request<SnapshotRequest>,
    ) -> Result<Response<SnapshotResponse>, Status> {
        Err(Status::unimplemented("Phase 3"))
    }

    async fn restore_snapshot(
        &self,
        _req: Request<RestoreRequest>,
    ) -> Result<Response<InstanceInfo>, Status> {
        Err(Status::unimplemented("Phase 3"))
    }

    // ── Fork (server-side streaming) ──────────────────────────────────────────
    type ForkStream = ReceiverStream<Result<InstanceInfo, Status>>;

    async fn fork(
        &self,
        _req: Request<ForkRequest>,
    ) -> Result<Response<Self::ForkStream>, Status> {
        let (tx, rx) = mpsc::channel(4);
        // Phase 3: spawn forking logic, send InstanceInfo for each child
        drop(tx); // closes the stream immediately (stub)
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── ADB shell (bidirectional streaming) ───────────────────────────────────
    type AdbShellStream = ReceiverStream<Result<AdbShellResponse, Status>>;

    async fn adb_shell(
        &self,
        _req: Request<Streaming<AdbShellRequest>>,
    ) -> Result<Response<Self::AdbShellStream>, Status> {
        let (tx, rx) = mpsc::channel(64);
        drop(tx);
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── Display streaming ─────────────────────────────────────────────────────
    type StreamDisplayStream = ReceiverStream<Result<DisplayFrame, Status>>;

    async fn stream_display(
        &self,
        _req: Request<DisplayStreamRequest>,
    ) -> Result<Response<Self::StreamDisplayStream>, Status> {
        let (tx, rx) = mpsc::channel(16);
        drop(tx);
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── Stop ──────────────────────────────────────────────────────────────────
    async fn stop_instance(
        &self,
        req: Request<StopRequest>,
    ) -> Result<Response<StopResponse>, Status> {
        let id = req.into_inner().instance_id;
        let removed = self.instances.write().await.remove(&id).is_some();
        Ok(Response::new(StopResponse { success: removed }))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Server bootstrap — mTLS required (client cert mandatory)
// ─────────────────────────────────────────────────────────────────────────────

pub async fn serve() -> Result<()> {
    let cert = fs::read("certs/server.crt")
        .context("Missing certs/server.crt — run: bash tools/gen_certs.sh")?;
    let key = fs::read("certs/server.key")
        .context("Missing certs/server.key")?;
    let ca = fs::read("certs/ca.crt")
        .context("Missing certs/ca.crt")?;

    let identity = tonic::transport::Identity::from_pem(cert, key);
    let client_ca = tonic::transport::Certificate::from_pem(ca);

    // tonic 0.12: client_auth_optional defaults to false → mTLS enforced
    let tls = tonic::transport::ServerTlsConfig::new()
        .identity(identity)
        .client_ca_root(client_ca);

    let addr = "[::1]:9550".parse().expect("hardcoded addr is valid");
    info!("gRPC/mTLS listening on {}", addr);

    Server::builder()
        .tls_config(tls)
        .context("Failed to configure TLS")?
        .add_service(TridentDaemonServer::new(TridentService::new()))
        .serve(addr)
        .await
        .context("gRPC server error")
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Generate a unique VM id from nanosecond timestamp.
/// Replace with a proper UUID crate if collisions become a concern.
fn unique_id() -> String {
    use std::time::SystemTime;
    let nanos = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos();
    format!("vm-{:08x}", nanos)
}

fn internal(e: anyhow::Error) -> Status {
    Status::internal(format!("{:#}", e))
}
